apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  labels:
    app: nextcloud
type: Opaque
data:
  NEXTCLOUD_ADMIN_PASSWORD: bmV4dGNsb3VkX3NlY3JldF9wYXNz
  NEXTCLOUD_ADMIN_USER: YWRtaW4=